/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;
/**
 *
 * @author LPG
 */
public class Administracion extends javax.swing.JFrame 
{
    /**
     * Creates new form Menu
     */
    public Administracion() 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PFondo = new javax.swing.JPanel();
        BSalir = new javax.swing.JButton();
        MInicial = new javax.swing.JMenuBar();
        MRegistro = new javax.swing.JMenu();
        RBuscar = new javax.swing.JMenu();
        MInventario = new javax.swing.JMenu();
        IBuscar = new javax.swing.JMenu();
        MActualizar = new javax.swing.JMenu();
        ABuscar = new javax.swing.JMenu();
        MVentas = new javax.swing.JMenu();
        VBuscar = new javax.swing.JMenu();
        MUsuarios = new javax.swing.JMenu();
        UBuscar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        PFondo.setBackground(new java.awt.Color(0, 153, 153));

        BSalir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BSalir.setText("Salir");
        BSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PFondoLayout = new javax.swing.GroupLayout(PFondo);
        PFondo.setLayout(PFondoLayout);
        PFondoLayout.setHorizontalGroup(
            PFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PFondoLayout.createSequentialGroup()
                .addContainerGap(508, Short.MAX_VALUE)
                .addComponent(BSalir)
                .addGap(32, 32, 32))
        );
        PFondoLayout.setVerticalGroup(
            PFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PFondoLayout.createSequentialGroup()
                .addContainerGap(310, Short.MAX_VALUE)
                .addComponent(BSalir)
                .addGap(34, 34, 34))
        );

        MRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/registro.png"))); // NOI18N
        MRegistro.setText("R. Productos.");
        MRegistro.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        RBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/buscar.png"))); // NOI18N
        RBuscar.setText("Buscar registro");
        RBuscar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        RBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RBuscarMouseClicked(evt);
            }
        });
        MRegistro.add(RBuscar);

        MInicial.add(MRegistro);

        MInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/inventario.png"))); // NOI18N
        MInventario.setText("I. Productos.");
        MInventario.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        IBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/buscar.png"))); // NOI18N
        IBuscar.setText("Buscar inventario");
        IBuscar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        IBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IBuscarMouseClicked(evt);
            }
        });
        MInventario.add(IBuscar);

        MInicial.add(MInventario);

        MActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/actualizar.png"))); // NOI18N
        MActualizar.setText("A. Inventario.");
        MActualizar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        ABuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/buscar.png"))); // NOI18N
        ABuscar.setText("Buscar actualización");
        ABuscar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ABuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ABuscarMouseClicked(evt);
            }
        });
        MActualizar.add(ABuscar);

        MInicial.add(MActualizar);

        MVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/ventas.png"))); // NOI18N
        MVentas.setText("V. Productos.");
        MVentas.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        VBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/buscar.png"))); // NOI18N
        VBuscar.setText("Buscar venta");
        VBuscar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        VBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VBuscarMouseClicked(evt);
            }
        });
        MVentas.add(VBuscar);

        MInicial.add(MVentas);

        MUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/usuarios.png"))); // NOI18N
        MUsuarios.setText("A. Usuarios.");
        MUsuarios.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        UBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesMenu/buscar.png"))); // NOI18N
        UBuscar.setText("Buscar usuario");
        UBuscar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        UBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UBuscarMouseClicked(evt);
            }
        });
        MUsuarios.add(UBuscar);

        MInicial.add(MUsuarios);

        setJMenuBar(MInicial);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RBuscarMouseClicked
        ABuscarRegistro ventana=new ABuscarRegistro();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RBuscarMouseClicked

    private void BSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSalirActionPerformed
        Inicio ventana=new Inicio();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BSalirActionPerformed

    private void IBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IBuscarMouseClicked
        ABuscarInventario ventana=new ABuscarInventario();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_IBuscarMouseClicked

    private void ABuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ABuscarMouseClicked
        ABuscarActualizacion ventana=new ABuscarActualizacion();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ABuscarMouseClicked

    private void VBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VBuscarMouseClicked
        ABuscarVenta ventana=new ABuscarVenta();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VBuscarMouseClicked

    private void UBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UBuscarMouseClicked
        ABuscarUsuario ventana=new ABuscarUsuario();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_UBuscarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ABuscar;
    private javax.swing.JButton BSalir;
    private javax.swing.JMenu IBuscar;
    private javax.swing.JMenu MActualizar;
    private javax.swing.JMenuBar MInicial;
    private javax.swing.JMenu MInventario;
    private javax.swing.JMenu MRegistro;
    private javax.swing.JMenu MUsuarios;
    private javax.swing.JMenu MVentas;
    private javax.swing.JPanel PFondo;
    private javax.swing.JMenu RBuscar;
    private javax.swing.JMenu UBuscar;
    private javax.swing.JMenu VBuscar;
    // End of variables declaration//GEN-END:variables
}
