/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

import com.devazt.networking.HttpClient;
import com.devazt.networking.OnHttpRequestComplete;
import com.devazt.networking.Response;
import org.json.JSONObject;
import java.io.*;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import com.itextpdf.kernel.geom.PageSize;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.property.HorizontalAlignment;
import com.itextpdf.layout.property.TextAlignment;
import java.awt.Desktop;
import java.io.File;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cliente
 */
public class AInsertarVenta extends javax.swing.JFrame {
    DefaultTableModel modelo;
    /**
     * Creates new form Ventas
     */
    public AInsertarVenta() 
    {
        initComponents();
        
        modelo = new DefaultTableModel();
        
        modelo.addColumn("Nombre");
        modelo.addColumn("Precio");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Monto parcial");
        
        this.Tabla.setModel(modelo);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jRadioButton1 = new javax.swing.JRadioButton();
        PFondo = new javax.swing.JPanel();
        LID = new javax.swing.JLabel();
        LNombre = new javax.swing.JLabel();
        LPrecio = new javax.swing.JLabel();
        LCantidad = new javax.swing.JLabel();
        LFecha = new javax.swing.JLabel();
        BAñadir = new javax.swing.JButton();
        BBuscar = new javax.swing.JButton();
        LTitulo = new javax.swing.JLabel();
        TID = new javax.swing.JTextField();
        TNombre = new javax.swing.JTextField();
        TPrecio = new javax.swing.JTextField();
        TCantidad = new javax.swing.JTextField();
        SP = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        TFecha = new javax.swing.JTextField();
        TExistencia = new javax.swing.JTextField();
        LExistencia = new javax.swing.JLabel();
        BEliminar = new javax.swing.JButton();
        LTotal = new javax.swing.JLabel();
        BFinalizarCompra = new javax.swing.JButton();
        BSalir = new javax.swing.JButton();
        TTotal = new javax.swing.JTextField();
        TResultado = new javax.swing.JTextField();
        BLimpiar = new javax.swing.JButton();
        TNew = new javax.swing.JTextField();
        BTicket = new javax.swing.JButton();
        LCompra = new javax.swing.JLabel();
        TCompra = new javax.swing.JTextField();
        BImprimir = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PFondo.setBackground(new java.awt.Color(0, 153, 153));

        LID.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        LID.setForeground(new java.awt.Color(255, 255, 255));
        LID.setText("Ingrese una ID:");

        LNombre.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        LNombre.setForeground(new java.awt.Color(255, 255, 255));
        LNombre.setText("Nombre:");

        LPrecio.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        LPrecio.setForeground(new java.awt.Color(255, 255, 255));
        LPrecio.setText("Precio:");

        LCantidad.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        LCantidad.setForeground(new java.awt.Color(255, 255, 255));
        LCantidad.setText("Cantidad:");

        LFecha.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        LFecha.setForeground(new java.awt.Color(255, 255, 255));
        LFecha.setText("Fecha de venta:");

        BAñadir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BAñadir.setText("Añadir");
        BAñadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BAñadirMouseClicked(evt);
            }
        });
        BAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAñadirActionPerformed(evt);
            }
        });

        BBuscar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BBuscar.setText("Buscar");
        BBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BBuscarMouseClicked(evt);
            }
        });
        BBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBuscarActionPerformed(evt);
            }
        });

        LTitulo.setBackground(new java.awt.Color(255, 255, 255));
        LTitulo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        LTitulo.setForeground(new java.awt.Color(255, 255, 255));
        LTitulo.setText("MENU DE VENTAS:");

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        SP.setViewportView(Tabla);

        LExistencia.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        LExistencia.setForeground(new java.awt.Color(255, 255, 255));
        LExistencia.setText("Cantidad en existencia:");

        BEliminar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BEliminar.setText("Eliminar");
        BEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEliminarActionPerformed(evt);
            }
        });

        LTotal.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        LTotal.setForeground(new java.awt.Color(255, 255, 255));
        LTotal.setText("Monto total:");

        BFinalizarCompra.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BFinalizarCompra.setText("Finalizar compra");
        BFinalizarCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BFinalizarCompraMouseClicked(evt);
            }
        });
        BFinalizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFinalizarCompraActionPerformed(evt);
            }
        });

        BSalir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BSalir.setText("Salir");
        BSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSalirActionPerformed(evt);
            }
        });

        BLimpiar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BLimpiar.setText("Limpiar");
        BLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLimpiarActionPerformed(evt);
            }
        });

        BTicket.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BTicket.setText("Generar ticket");
        BTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTicketActionPerformed(evt);
            }
        });

        LCompra.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        LCompra.setForeground(new java.awt.Color(255, 255, 255));
        LCompra.setText("Numero de compra:");

        BImprimir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BImprimir.setText("Imprimir");
        BImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PFondoLayout = new javax.swing.GroupLayout(PFondo);
        PFondo.setLayout(PFondoLayout);
        PFondoLayout.setHorizontalGroup(
            PFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PFondoLayout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(LTitulo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PFondoLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(PFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PFondoLayout.createSequentialGroup()
                        .addGroup(PFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TNew, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PFondoLayout.createSequentialGroup()
                                .addComponent(LID)
                                .addGap(32, 32, 32)
                                .addGroup(PFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BAñadir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TID, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PFondoLayout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(TNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PFondoLayout.createSequentialGroup()
                                .addGroup(PFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LExistencia)
                                    .addComponent(LNombre)
                                    .addComponent(LPrecio)
                                    .addComponent(LFecha)
                                    .addComponent(LTotal)
                                    .addComponent(LCantidad)
                                    .addComponent(LCompra))
                                .addGap(18, 18, 18)
                                .addGroup(PFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TFecha)
                                    .addComponent(TTotal)
                                    .addComponent(TCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(TPrecio)
                                    .addComponent(TExistencia, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(TCompra)))))
                    .addComponent(SP, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                    .addGroup(PFondoLayout.createSequentialGroup()
                        .addComponent(BFinalizarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BTicket)
                        .addGap(18, 18, 18)
                        .addComponent(BImprimir))
                    .addComponent(TResultado)
                    .addGroup(PFondoLayout.createSequentialGroup()
                        .addComponent(BLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        PFondoLayout.setVerticalGroup(
            PFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PFondoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(LTitulo)
                .addGap(18, 18, 18)
                .addGroup(PFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PFondoLayout.createSequentialGroup()
                        .addGroup(PFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LPrecio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TExistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LExistencia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LCantidad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LFecha)
                            .addComponent(TFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LTotal)
                            .addComponent(TTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PFondoLayout.createSequentialGroup()
                        .addGroup(PFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BBuscar)
                        .addGap(36, 36, 36)
                        .addComponent(BAñadir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BEliminar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LCompra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(SP, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BFinalizarCompra)
                    .addComponent(BTicket)
                    .addComponent(BImprimir))
                .addGap(18, 18, 18)
                .addComponent(TResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BLimpiar)
                    .addComponent(BSalir))
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BBuscarMouseClicked
        try
        {
            HttpClient cliente=new HttpClient (new OnHttpRequestComplete() 
            {
                @Override
                public void onComplete(Response status) 
                {
                    if(status.isSuccess())
                    {
                        JSONObject r=new JSONObject(status.getResult());
                        String cantidadEWeb=r.getJSONObject("0").get("cantidad").toString();

                        TExistencia.setText(cantidadEWeb);
                    }
                    throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                }
            });
            String id = TID.getText();
            cliente.excecute("http://127.0.0.1/Api/i_productos.php?id_producto="+id);
        }
        catch(UnsupportedOperationException e){}
    }//GEN-LAST:event_BBuscarMouseClicked

    private void BBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBuscarActionPerformed
        try
        {
            HttpClient cliente=new HttpClient (new OnHttpRequestComplete() 
            {
                @Override
                public void onComplete(Response status) 
                {
                    if(status.isSuccess())
                    {
                        JSONObject r=new JSONObject(status.getResult());
                        String nombreWeb=r.getJSONObject("0").get("nombre").toString();
                        String precioWeb=r.getJSONObject("0").get("precio").toString();

                        TNombre.setText(nombreWeb);
                        TPrecio.setText(precioWeb);
                    }
                    throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                }
            });
            String id = TID.getText();
            cliente.excecute("http://127.0.0.1/Api/r_productos.php?id_producto="+id);
        }
        catch(UnsupportedOperationException e){}
    }//GEN-LAST:event_BBuscarActionPerformed

    private void BAñadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BAñadirMouseClicked
        String info[]=new String[4];
        
        info[0]=TNombre.getText();
        
        double precio, cantidad, monto;

        info[1]=TPrecio.getText();
        info[2]=TCantidad.getText();
        
        precio=Double.parseDouble(TPrecio.getText());
        cantidad=Double.parseDouble(TCantidad.getText());
        
        monto=precio*cantidad;
        
        String m = String.valueOf(monto);
        
        info[3]=m;
        
        modelo.addRow(info); 

        Total();
        
        TID.setText("");
        TNombre.setText("");
        TPrecio.setText("");
        TCantidad.setText("");
        TExistencia.setText("");  
    }//GEN-LAST:event_BAñadirMouseClicked

    private void BAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAñadirActionPerformed
        try
        {
            HttpClient cliente=new HttpClient (new OnHttpRequestComplete() 
            {
                @Override
                public void onComplete(Response status) 
                {
                    if(status.isSuccess())
                    {
                        TNew.setText(status.getResult());
                    }
                    throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                }
            });
            String id = TID.getText();
            String cantidad = TCantidad.getText();
            
            cliente.excecute("http://127.0.0.1/Api/i_productosA.php?id_producto="+id+"&cantidad="+cantidad);
        }
        catch(UnsupportedOperationException e){}
    }//GEN-LAST:event_BAñadirActionPerformed

    private void BEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEliminarActionPerformed
        int fila=Tabla.getSelectedRow();
        if(fila>=0)
        {
            modelo.removeRow(fila);
        }
        else{}
    }//GEN-LAST:event_BEliminarActionPerformed

    
    private void BSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSalirActionPerformed
        Administracion ventana=new Administracion();
        ventana.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BSalirActionPerformed

    private void BFinalizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFinalizarCompraActionPerformed
        try
        {
            HttpClient cliente=new HttpClient (new OnHttpRequestComplete() 
            {
                @Override
                public void onComplete(Response status) 
                {
                    if(status.isSuccess())
                    {
                        TResultado.setText(status.getResult());
                    }
                    throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
                }
            });
            
            String fecha = TFecha.getText();
            String monto = TTotal.getText();
            
            cliente.excecute("http://127.0.0.1/Api/v_productosR.php?&fecha_venta="+fecha+"&monto_total="+monto);
        }
        catch(UnsupportedOperationException e){}
    }//GEN-LAST:event_BFinalizarCompraActionPerformed

    private void BFinalizarCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BFinalizarCompraMouseClicked
        
    }//GEN-LAST:event_BFinalizarCompraMouseClicked

    private void BLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLimpiarActionPerformed
        TResultado.setText("");
        TNew.setText("");
        TFecha.setText("");
        TTotal.setText("");
        
        int fila=Tabla.getRowCount();
        for (int i = fila-1; i >= 0; i--)
        {
            modelo.removeRow(i);
        }
        
    }//GEN-LAST:event_BLimpiarActionPerformed

    private void BTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTicketActionPerformed
        try 
        {
            String compra = TCompra.getText();
            String fecha = TFecha.getText();
  
            File file = new File("C:/Ticket/"+compra+".pdf");
            file.getParentFile().mkdirs();
            PdfWriter writer;
      
            writer = new PdfWriter(file);
            PdfDocument pdf = new PdfDocument(writer);
            try (Document document = new Document(pdf, PageSize.A7) // Tamaño de un ticket
            ) {
                document.setMargins(10, 10, 10, 10);
                Paragraph header = new Paragraph("Ticket de Compra").setTextAlignment(TextAlignment.CENTER);
                
                
                document.add(header);
                document.add(new Paragraph("----------------------------------------"));
                Paragraph info = new Paragraph("Número de Factura:"+compra+"\nFecha:"+fecha);
                document.add(info);
                document.add(new Paragraph("----------------------------------------"));
                Table table = new Table(4);
                table.addCell("Nombre");
                table.addCell("Precio");
                table.addCell("Cantidad");
                table.addCell("Monto");
                
                for (int i = 0; i < Tabla.getRowCount(); i++)
                {
                    table.addCell(Tabla.getValueAt(i,0).toString());
                    table.addCell(Tabla.getValueAt(i,1).toString());
                    table.addCell(Tabla.getValueAt(i,2).toString());
                    table.addCell(Tabla.getValueAt(i,3).toString());
                }
                
                document.add(table.setHorizontalAlignment(HorizontalAlignment.CENTER));
                
                document.add(new Paragraph("----------------------------------------"));
                String total = TTotal.getText();
                Paragraph totalInfo = new Paragraph("Total:$"+total).setTextAlignment(TextAlignment.RIGHT);
                document.add(totalInfo);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AInsertarVenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BTicketActionPerformed

    private void BImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BImprimirActionPerformed
        String filepad="C:/Ticket/1.pdf";
        File pdfFile = Paths.get(filepad).toFile();
        if (Desktop.isDesktopSupported()) {
            Desktop desktop = Desktop.getDesktop();
            if (desktop.isSupported(Desktop.Action.PRINT)) {
                try {
                    desktop.print(pdfFile);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            } else {
                System.out.println("La acción de impresión no es compatible.");
            }
        } else {
            System.out.println("El soporte de Desktop no está disponible en este sistema.");
       }
    }//GEN-LAST:event_BImprimirActionPerformed

    public void Total()
    {
        double Fila;
        double MTotal = 0;
        
        for (int i = 0; i < Tabla.getRowCount(); i++) 
        {
            Fila = Double.parseDouble(Tabla.getValueAt(i,3).toString());
            MTotal += Fila;
        }
        TTotal.setText(""+MTotal);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AInsertarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AInsertarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AInsertarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AInsertarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AInsertarVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAñadir;
    private javax.swing.JButton BBuscar;
    private javax.swing.JButton BEliminar;
    private javax.swing.JButton BFinalizarCompra;
    private javax.swing.JButton BImprimir;
    private javax.swing.JButton BLimpiar;
    private javax.swing.JButton BSalir;
    private javax.swing.JButton BTicket;
    private javax.swing.JLabel LCantidad;
    private javax.swing.JLabel LCompra;
    private javax.swing.JLabel LExistencia;
    private javax.swing.JLabel LFecha;
    private javax.swing.JLabel LID;
    private javax.swing.JLabel LNombre;
    private javax.swing.JLabel LPrecio;
    private javax.swing.JLabel LTitulo;
    private javax.swing.JLabel LTotal;
    private javax.swing.JPanel PFondo;
    private javax.swing.JScrollPane SP;
    private javax.swing.JTextField TCantidad;
    private javax.swing.JTextField TCompra;
    private javax.swing.JTextField TExistencia;
    private javax.swing.JTextField TFecha;
    private javax.swing.JTextField TID;
    private javax.swing.JTextField TNew;
    private javax.swing.JTextField TNombre;
    private javax.swing.JTextField TPrecio;
    private javax.swing.JTextField TResultado;
    private javax.swing.JTextField TTotal;
    private javax.swing.JTable Tabla;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
